import type { TreeState } from "./types";

export const initialTree: TreeState = {
  root: {
    id: "root",
    label: "Is this decision time-sensitive?",
    kind: "decision",
    x: 360,
    y: 90,
    yes: "n1",
    no: "n2",
    colorIdx: 0,
    isRoot: true,
  },
  n1: {
    id: "n1",
    label: "Act immediately",
    kind: "outcome",
    x: 160,
    y: 260,
    yes: null,
    no: null,
    colorIdx: 1,
  },
  n2: {
    id: "n2",
    label: "Do you have enough information?",
    kind: "decision",
    x: 560,
    y: 260,
    yes: "n3",
    no: "n4",
    colorIdx: 2,
  },
  n3: {
    id: "n3",
    label: "Make the decision now",
    kind: "outcome",
    x: 440,
    y: 430,
    yes: null,
    no: null,
    colorIdx: 3,
  },
  n4: {
    id: "n4",
    label: "Gather more data first",
    kind: "outcome",
    x: 680,
    y: 430,
    yes: null,
    no: null,
    colorIdx: 4,
  },
};

